// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Imam Taufiq Ponco Utomo",
            "email": "imamtaufiqponco@gmail.co.id"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Get Health API Check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Get Health API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetHealth_Result"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.GetHealth_Result": {
            "type": "object",
            "properties": {
                "appVersion": {
                    "type": "string",
                    "example": "v0.1.0"
                },
                "buildSignature": {
                    "type": "string",
                    "example": "2b38f457-577f-423b-a7c0-16c50a86398c"
                },
                "serverTime": {
                    "type": "string",
                    "example": "2023-03-14T22:59:10.155009095+07:00"
                },
                "uptime": {
                    "type": "string",
                    "example": "1m39.5398474s"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "Boilerplate - Service Using Gin Framework",
	Description:      "RBoilerplate - Service Using Gin Framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
